eureka:
  instance:
    metadataMap:
      zone: zona2
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/
server:  
  port: ${PORT:9002}

#
demo:
  nombreArchivo: servicio-cliente-zona2.yml