# Información servicio
spring:
  application:
    name: servicio-de-configuracion
  main:    allow-bean-definition-overriding: true
  cloud:    config:      server:
        monitor:
          github:
            enabled: true          git:
          uri: https://github.com/netec-dev/com-netec-c-microservicios-spring-cloud-config-repositorio.git
          default-label: SCBus
          #En un repositorio público no son requeridas credenciales
          #username: ${github.username}
          #password: ${github.password}
          cloneOnStart: true  rabbitmq:    host: localhost
    port: 5672
    username: guest
    password: guest
#
management:
  security:
    enabled: false
# Información servidor
server:  
  port: ${PORT:2001}
# Servidor Eureka 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/
#