eureka:
  instance:
    metadataMap:
      zone: zona3
  client:
    serviceUrl:
      defaultZone: http://localhost:3001/eureka/
server:  
  port: ${PORT:9003}

#
demo:
  nombreArchivo: servicio-cliente-zona3.yml