#
spring:  
  application:
    name: servicio-de-descubrimiento
server:
  port: ${PORT:3001} 
#
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/